version: '3'
services: 
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3100 -b '0.0.0.0'"
    volumes:
      - .:/app
    env_file: .env
    environment:
      POSTGRES_HOST: db
      RAILS_ENV: development
    ports: 
      - "3100:3100"
    depends_on: 
      - db